channels:
- conda-forge
dependencies:
- python=3.11.4
- pip<=23.2.1
- pip:
  - mlflow==2.14.3
  - cloudpickle==2.2.1
  - numpy==1.24.4
  - packaging==23.1
  - psutil==5.9.5
  - pyyaml==6.0.1
  - scikit-learn==1.3.0
  - scipy==1.14.1
name: mlflow-env
