# Automatic deployment workflow
name: ML Auto Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
    shadow_deployment:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up python
          uses: actions/setup-python@v5
          with:
            python-version: '3.11'

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install mlflow==2.12.1 loguru
        
        - name: Run docker-compose
          uses: hoverkraft-tech/compose-action@v2.0.1
          with:
              compose-file: "docker-compose.yml"    
        
        - name: Run Automatic deployment
          env:
            MLFLOW_TRACKING_URI: ${{ vars.MLFLOW_TRACKING_URI }}
            MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
            MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
          run: |
            python mlflowmodeldeployment.py